name: CI Pipeline

on:
  pull_request:
    branches:
      - master
    paths-ignore: # Ignorer certains fichiers si nécessaire
      - '.github/**'
      - 'README.md'

jobs:
  tests:
    name: Run Tests and Code Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read # Lecture des fichiers
      pull-requests: write # Permet de commenter le PR avec les résultats de SonarCloud

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Node.js et les dépendances
      - name: Installer Node.js et les dépendances
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Remplacez par votre version Node.js

      # Installer les dépendances npm
      - name: Installer les dépendances npm
        run: npm install

      # Étape 3 : Installation des navigateurs Playwright
      - name: Installation des navigateurs Playwright
        run: npx playwright install --with-deps

      # Étape 4 : Lancer le build
      - name: Lancer le build
        run: npm run build

      # Étape 5 : Lancer les tests unitaires
      - name: Lancer les tests unitaires
        run: npm run lint:ci && npm run test:ci

      # Étape 6 : Lancer les tests E2E avec Playwright
      - name: Lancer les tests E2E avec Playwright
        run: npm run test:e2e

      # Étape 7 : SonarCloud Analysis
      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@e3b481c5d50b1eeac5034f92d6cf9b62d3cf5e7d
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Créez un secret dans "Settings > Secrets and variables"
          # Pour le debug, sinon, retirez-le après avoir trouvé le problème
          SONAR_SCANNER_DEBUG: false
        with:
          args: >
            -Dsonar.projectKey=stef38-code_app-nounou
            -Dsonar.organization=stef38-code
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.inclusions=**/*.ts
            -Dsonar.test.inclusions=**/*.spec.ts,**/*.test.ts
